### ISSUE TITLE
can't find the code

### ISSUE THREAD

**Issue by xpinus** [alibraytee/UDA-TFL#1]
so where the code of  'Unsupervised Domain Adaptation based Tensor
Feature Learning with Structure Preservation'

**Comment by sjy-xixi** [comment]
Have you found the code now

**Comment by xpinus** [comment]
Still don't see any code
![image](https://user-images.githubusercontent.com/27531586/177489142-d838428b-06e3-4d8c-8baf-f2d79e381903.png)
